##############################################################
# Imixs-Admin - Docker-Compose Stack
#
# - Postgres DB with volume 
# - Imixs-Admin running on JDK 11 - Wildfly 27
##############################################################
version: "3.1"
services:


  imixs-admin:
    image: imixs/imixs-admin
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
    ports:
      - "8080:8080"
      - "8787:8787"
    volumes:
      - ./docker/deployments:/opt/jboss/wildfly/standalone/deployments/
 

# Sample DB
  imixs-db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflowdb
    volumes: 
      - dbsampledata:/var/lib/postgresql/data
    
# Imixs-Process-Manager    
  imixs-sample-app:
    image: imixs/imixs-process-manager
    environment:
      TZ: "CET" 
      LANG: "en_US.UTF-8"  
      JAVA_OPTS: "-Dnashorn.args=--no-deprecation-warning"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://imixs-db/workflowdb"
    ports:
      - "8081:8080"
      - "8789:8787"
      - "9991:9990"   

volumes:
  dbsampledata:

