version: "3"
services:

  imixsadmin-app:
    #image: imixs/imixs-admin:5.1.6
    image: imixs/imixs-admin:latest
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
    ports:
      - "8080:8080"
      - "8787:8787"
      #- "9990:9990"
      #- "8443:8443"    
    volumes:
      - ./docker/deployments:/opt/jboss/wildfly/standalone/deployments/
 

    
 